// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        networksystem.dll
// classes:       1
// enums:         0
// generated_at:  2026-05-11T04:26:09.708576+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

namespace sdk::networksystem {

    class ChangeAccessorFieldPathIndex_t;

    // ChangeAccessorFieldPathIndex_t
    //   fields: 1
    class ChangeAccessorFieldPathIndex_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_Value                                         , 0x0) // int32
    };

} // namespace sdk::networksystem
