// Generated by cs2-sdk — https://cs2-sdk.com
//
// module:        pulse_system.dll
// classes:       33
// enums:         2
// generated_at:  2026-05-11T04:26:09.708576+00:00
//
// Use:
//   auto* pawn = reinterpret_cast<C_CSPlayerPawn*>(addr);
//   pawn->m_iHealth() = 100;

#pragma once
#include "cs2sdk_macros.hpp"

#include "animationsystem_dll.hpp"

namespace sdk::pulse_system {

    class CPulseCell_Step_TestDomainDestroyFakeEntity;
    class CPulseCell_Test_NoInflow;
    class CPulseGraphInstance_TestDomain_FakeEntityOwner;
    class CTestDomainDerived_Cursor;
    class CPulseTestFuncs_LibraryA;
    class CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView;
    class CPulseCell_Test_MultiOutflow_WithParams;
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding_CursorState_t;
    class CPulseTurtleGraphicsCursor;
    class CPulseCell_TestWaitWithCursorState_CursorState_t;
    class CPulseCell_Test_MultiInflow_NoDefault;
    class CPulseCell_Value_TestValue50;
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding;
    class TestComponent_tAPI;
    class CPulseCell_Step_TestDomainTracepoint;
    class CPulseGraphInstance_TestDomain_Derived;
    class CPulseGraphInstance_TestDomain;
    class CPulseCell_Outflow_TestExplicitYesNo;
    class CPulseCell_Outflow_TestRandomYesNo;
    class FakeEntity_tAPI;
    class CPulseCell_Test_MultiInflow_WithDefault;
    class CPulseGraphInstance_TurtleGraphics;
    class CPulseCell_Val_TestDomainGetEntityName;
    class CPulseCell_TestWaitWithCursorState;
    class FakeEntityDerivedB_tAPI;
    class CPulseCell_Val_TestDomainFindEntityByName;
    class CPulseCell_Step_TestDomainEntFire;
    class FakeEntityDerivedA_tAPI;
    class CPulseCell_ExampleSelector;
    class CPulseCell_ExampleCriteria_Criteria_t;
    class CPulseCell_ExampleCriteria;
    class CPulseCell_Step_TestDomainCreateFakeEntity;
    class TestComponent_t;

    enum class PulseTestEnumShape_t : std::uint32_t {
        CIRCLE = 0x64,
        SQUARE = 0xC8,
        TRIANGLE = 0x12C,
    };

    enum class PulseTestEnumColor_t : std::uint32_t {
        BLACK = 0x0,
        WHITE = 0x1,
        RED = 0x2,
        GREEN = 0x3,
        BLUE = 0x4,
    };

    // CPulseGraphInstance_TestDomain
    //   fields: 9
    class CPulseGraphInstance_TestDomain {
    public:
        SCHEMA_FIELD(bool                            , m_bIsRunningUnitTests                           , 0x130) // bool
        SCHEMA_FIELD(bool                            , m_bExplicitTimeStepping                         , 0x131) // bool
        SCHEMA_FIELD(bool                            , m_bExpectingToDestroyWithYieldedCursors         , 0x132) // bool
        SCHEMA_FIELD(bool                            , m_bQuietTracepoints                             , 0x133) // bool
        SCHEMA_FIELD(bool                            , m_bExpectingCursorTerminatedDueToMaxInstructions, 0x134) // bool
        SCHEMA_FIELD(std::int32_t                    , m_nCursorsTerminatedDueToMaxInstructions        , 0x138) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nNextValidateIndex                            , 0x13C) // int32
        SCHEMA_FIELD(CUtlVector<CUtlString>          , m_Tracepoints                                   , 0x140) // CUtlVector<CUtlString>
        SCHEMA_FIELD(bool                            , m_bTestYesOrNoPath                              , 0x158) // bool
    };

    // CPulseCell_Outflow_TestRandomYesNo
    //   fields: 2
    class CPulseCell_Outflow_TestRandomYesNo {
    public:
        SCHEMA_FIELD(::sdk::animationsystem::CPulse_OutflowConnection, m_Yes                                           , 0x48) // CPulse_OutflowConnection
        SCHEMA_FIELD(::sdk::animationsystem::CPulse_OutflowConnection, m_No                                            , 0x90) // CPulse_OutflowConnection
    };

    // CPulseCell_Test_MultiOutflow_WithParams
    //   fields: 2
    class CPulseCell_Test_MultiOutflow_WithParams {
    public:
        SCHEMA_FIELD(::sdk::animationsystem::SignatureOutflow_Continue, m_Out1                                          , 0x48) // SignatureOutflow_Continue
        SCHEMA_FIELD(::sdk::animationsystem::SignatureOutflow_Continue, m_Out2                                          , 0x90) // SignatureOutflow_Continue
    };

    // CPulseCell_Test_MultiOutflow_WithParams_Yielding::CursorState_t
    //   fields: 1
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding_CursorState_t {
    public:
        SCHEMA_FIELD(std::int32_t                    , nTestStep                                       , 0x0) // int32
    };

    // CPulseCell_Test_MultiInflow_NoDefault
    //   fields: 0
    class CPulseCell_Test_MultiInflow_NoDefault {
    public:
    };

    // CPulseCell_Outflow_TestExplicitYesNo
    //   fields: 2
    class CPulseCell_Outflow_TestExplicitYesNo {
    public:
        SCHEMA_FIELD(::sdk::animationsystem::CPulse_OutflowConnection, m_Yes                                           , 0x48) // CPulse_OutflowConnection
        SCHEMA_FIELD(::sdk::animationsystem::CPulse_OutflowConnection, m_No                                            , 0x90) // CPulse_OutflowConnection
    };

    // CPulseGraphInstance_TurtleGraphics
    //   fields: 0
    class CPulseGraphInstance_TurtleGraphics {
    public:
    };

    // CPulseCell_Step_TestDomainDestroyFakeEntity
    //   fields: 0
    class CPulseCell_Step_TestDomainDestroyFakeEntity {
    public:
    };

    // CPulseCell_ExampleSelector
    //   fields: 1
    class CPulseCell_ExampleSelector {
    public:
        SCHEMA_FIELD(::sdk::animationsystem::PulseSelectorOutflowList_t, m_OutflowList                                   , 0x48) // PulseSelectorOutflowList_t
    };

    // CPulseCell_ExampleCriteria
    //   fields: 0
    class CPulseCell_ExampleCriteria {
    public:
    };

    // FakeEntityDerivedA_tAPI
    //   fields: 0
    class FakeEntityDerivedA_tAPI {
    public:
    };

    // CPulseCell_TestWaitWithCursorState
    //   fields: 3
    class CPulseCell_TestWaitWithCursorState {
    public:
        SCHEMA_FIELD(::sdk::animationsystem::CPulse_ResumePoint, m_WakeResume                                    , 0x48) // CPulse_ResumePoint
        SCHEMA_FIELD(::sdk::animationsystem::CPulse_ResumePoint, m_WakeCancel                                    , 0x90) // CPulse_ResumePoint
        SCHEMA_FIELD(::sdk::animationsystem::CPulse_ResumePoint, m_WakeFail                                      , 0xD8) // CPulse_ResumePoint
    };

    // FakeEntity_tAPI
    //   fields: 0
    class FakeEntity_tAPI {
    public:
    };

    // CPulseCell_Step_TestDomainEntFire
    //   fields: 1
    class CPulseCell_Step_TestDomainEntFire {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_Input                                         , 0x48) // CUtlString
    };

    // TestComponent_tAPI
    //   fields: 0
    class TestComponent_tAPI {
    public:
    };

    // CPulseCell_TestWaitWithCursorState::CursorState_t
    //   fields: 2
    class CPulseCell_TestWaitWithCursorState_CursorState_t {
    public:
        SCHEMA_FIELD(float                           , flWaitValue                                     , 0x0) // float32
        SCHEMA_FIELD(bool                            , bFailOnCancel                                   , 0x4) // bool
    };

    // CPulseCell_ExampleCriteria::Criteria_t
    //   fields: 3
    class CPulseCell_ExampleCriteria_Criteria_t {
    public:
        SCHEMA_FIELD(float                           , m_flFloatValue1                                 , 0x0) // float32
        SCHEMA_FIELD(float                           , m_flFloatValue2                                 , 0x4) // float32
        SCHEMA_FIELD(bool                            , m_bMyBool                                       , 0x8) // bool
    };

    // CPulseCell_Value_TestValue50
    //   fields: 0
    class CPulseCell_Value_TestValue50 {
    public:
    };

    // TestComponent_t
    //   fields: 1
    class TestComponent_t {
    public:
        SCHEMA_FIELD(::CUtlString                    , m_ComponentData                                 , 0x8) // CUtlString
    };

    // CTestDomainDerived_Cursor
    //   fields: 2
    class CTestDomainDerived_Cursor {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nCursorValueA                                 , 0xD8) // int32
        SCHEMA_FIELD(std::int32_t                    , m_nCursorValueB                                 , 0xDC) // int32
    };

    // CPulseTurtleGraphicsCursor
    //   fields: 4
    class CPulseTurtleGraphicsCursor {
    public:
        SCHEMA_FIELD(::Color                         , m_Color                                         , 0xD8) // Color
        SCHEMA_FIELD(::Vector2D                      , m_vPos                                          , 0xDC) // Vector2D
        SCHEMA_FIELD(float                           , m_flHeadingDeg                                  , 0xE4) // float32
        SCHEMA_FIELD(bool                            , m_bPenUp                                        , 0xE8) // bool
    };

    // CPulseGraphInstance_TestDomain_Derived
    //   fields: 1
    class CPulseGraphInstance_TestDomain_Derived {
    public:
        SCHEMA_FIELD(std::int32_t                    , m_nInstanceValueX                               , 0x160) // int32
    };

    // CPulseGraphInstance_TestDomain_FakeEntityOwner
    //   fields: 0
    class CPulseGraphInstance_TestDomain_FakeEntityOwner {
    public:
    };

    // CPulseCell_Step_TestDomainCreateFakeEntity
    //   fields: 0
    class CPulseCell_Step_TestDomainCreateFakeEntity {
    public:
    };

    // CPulseTestFuncs_LibraryA
    //   fields: 0
    class CPulseTestFuncs_LibraryA {
    public:
    };

    // CPulseCell_Test_NoInflow
    //   fields: 0
    class CPulseCell_Test_NoInflow {
    public:
    };

    // CPulseCell_Val_TestDomainFindEntityByName
    //   fields: 0
    class CPulseCell_Val_TestDomainFindEntityByName {
    public:
    };

    // CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView
    //   fields: 0
    class CPulseGraphInstance_TestDomain_UseReadOnlyBlackboardView {
    public:
    };

    // CPulseCell_Test_MultiOutflow_WithParams_Yielding
    //   fields: 5
    class CPulseCell_Test_MultiOutflow_WithParams_Yielding {
    public:
        SCHEMA_FIELD(::sdk::animationsystem::SignatureOutflow_Continue, m_Out1                                          , 0x48) // SignatureOutflow_Continue
        SCHEMA_FIELD(::sdk::animationsystem::SignatureOutflow_Continue, m_AsyncChild1                                   , 0x90) // SignatureOutflow_Continue
        SCHEMA_FIELD(::sdk::animationsystem::SignatureOutflow_Continue, m_AsyncChild2                                   , 0xD8) // SignatureOutflow_Continue
        SCHEMA_FIELD(::sdk::animationsystem::SignatureOutflow_Resume, m_YieldResume1                                  , 0x120) // SignatureOutflow_Resume
        SCHEMA_FIELD(::sdk::animationsystem::SignatureOutflow_Resume, m_YieldResume2                                  , 0x168) // SignatureOutflow_Resume
    };

    // CPulseCell_Step_TestDomainTracepoint
    //   fields: 0
    class CPulseCell_Step_TestDomainTracepoint {
    public:
    };

    // CPulseCell_Val_TestDomainGetEntityName
    //   fields: 0
    class CPulseCell_Val_TestDomainGetEntityName {
    public:
    };

    // CPulseCell_Test_MultiInflow_WithDefault
    //   fields: 0
    class CPulseCell_Test_MultiInflow_WithDefault {
    public:
    };

    // FakeEntityDerivedB_tAPI
    //   fields: 0
    class FakeEntityDerivedB_tAPI {
    public:
    };

} // namespace sdk::pulse_system
